accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    
    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
    
]

kadaiproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('status_app.urls')),
    
    path('',include('accounts.urls')),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),



    
    
]

status_app/urls.py
from django.urls import path
from . import views
#URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name ='status_app'
#URLパターンを登録するためのリスト
urlpatterns = [
    
   path('course/', views.CourseView.as_view(),name='course'),
   
    path('user-list/<int:user>',
         views.UserView.as_view(),
         name='user_list'),
   path('access/', views.AccessView.as_view(),name='access'),
    
    #http(s):// ホスト名/以下のパスが''(無し)の場合
    #viewsモジュールのindexviewを実行
    #URLパターン名は'index'
    path('user/', views.MyIndexView.as_view(),name='index')
]

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

accounts/forms.py
# UserCreationFormクラスをインポート
from django.contrib.auth.forms import UserCreationForm
# models.pyで定義したカスタムUserモデルをインポート
from django import forms
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    '''UserCreationFormのサブクラス
    '''
    class Meta:
        '''UserCreationFormのインナークラス
        
        Attributes:
          model:連携するUserモデル
          fields:フォームで使用するフィールド
        '''
        # 連携するUserモデルを設定
        model = CustomUser
        # フォームで使用するフィールドを設定
        # ユーザー名、メールアドレス、パスワード、パスワード(確認用)
        fields = ('username', 'email', 'password1', 'password2')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        
        self.fields['username'].widget.attrs['placeholder']=\
            'お名前を入力してください'
        
        self.fields['email'].widget.attrs['placeholder']=\
        'メールアドレスを入力してください'
        
        self.fields['password1'].widget.attrs['placeholder']=\
        'パスワードを入力してください'
        
        self.fields['password2'].widget.attrs['placeholder']=\
        '同じパスワードを入力してください'
        
        
        
    
        
      
        
        

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    '''サインアップページのビュー
    
    '''
    # forms.pyで定義したフォームのクラス
    form_class = CustomUserCreationForm
    # レンダリングするテンプレート
    template_name = "signup.html"
    # サインアップ完了後のリダイレクト先のURLパターン
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録を行う
        
        parameters:
          form(django.forms.Form):
            form_classに格納されているCustomUserCreationFormオブジェクト
        Return:
          HttpResponseRedirectオブジェクト:
            スーパークラスのform_valid()の戻り値を返すことで、
            success_urlで設定されているURLにリダイレクトさせる
        '''
        # formオブジェクトのフィールドの値をデータベースに保存
        user = form.save()
        self.object = user
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    '''サインアップ成功ページのビュー
    
    '''
    # レンダリングするテンプレート
    template_name = "signup_success.html"

accounts/templates/login.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- タイトル変更 -->
    <title>Log in</title>

    <!-- <link rel="canonical"...>を削除 -->    

    <!-- Bootstrap core CSS -->
    <!--
    Bootstrap core CSSを読み込むコードをBootstrapからコピーして
    <link>タグを書き換え -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
          crossorigin="anonymous">
    

    
    <!-- Custom styles for this template -->
    <!-- 「static/css/signin.css」の読み込み -->
    <link href={% static "css/style.css" %}
          rel="stylesheet">
  </head>
  <body id="login1" >    
    <main class="form-signin">
      <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
      {% if form.errors %}
        <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}
      <!-- ログインのフォームを配置 -->
      <div class="login-container mannnaka">
      <form method="post" class="mannnaka">
        {% csrf_token %}
        <!-- Bootstrapのロゴを表示 -->
        <!-- 「static/img/bootstrap-logo.svg」の読み込み -->
        <img class="mb-4"
             src={% static "img/bootstrap-logo.svg" %}
             alt="" width="72"
             height="57">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
        <!--
        <div class="form-floating">～</div>の2つのブロックを削除して
        以下に書き換え
        -->
        <!-- Usernameのラベル(非表示) -->
        <label for="Username" class="visually-hidden">
          User name</label>
        <!-- usernameの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名username -->
        <input type="text"
               name="username"
               id="id_username"
               maxlength="150"
               autocapitalize="none"
               autocomplete="username"
               class="form-control"
               placeholder="ユーザー名"
               required autofocus>
        <!-- Passwordのラベル(非表示) -->
        <label for="Password" class="visually-hidden">
          Password</label>
        <!-- passwordの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名password -->
        <input type="password"
               name="password"
               id="id_password"
               autocomplete="current-password"
               class="form-control"
               placeholder="パスワード"
               required autofocus>
        
        <!-- <button>～</button>を書き換えてログインボタンを配置 -->
            <input class="w-100 btn btn-lg btn-primary"
                   type="submit"
                   value="ログイン">
        
        <!-- パスワードリセットページのリンクテキスト -->
        <br><br>
        <div class="footer">
          <p>アカウントをお持ちでないですか？ </p>
          <a href="{% url 'accounts:signup' %}"> 新規登録</a>
        </div>
        <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか?</a><p>
        <!-- ログイン直後のリダイレクト先(トップページ)のURLパターンを設定 -->
        <input type="hidden"
               name="next"
               value="{% url 'status_app:index' %}">
      </form>
    </div>
    </main>   
  </body>
</html>

accounts/templates/logout.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Log out{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-4を入れる
               列の上下パディングはpy-4 -->
          <div class="col offset-4 py-4">

          <h3>ログアウトしました</h3>
          <!-- トップページのリンクテキスト -->
          <p><a href="{% url 'status_app:index' %}">トップページへ</a><p>
      {% endblock %}

accounts/templates/password_reset.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Reset password{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の上下パディングはpy-4-->
          <div class="col py-4">
            <hr>
            <h3>パスワードをリセットしますか?</h3>
            <p>
              登録済みのメールアドレスを入力してください。
              パスワードリセットのリンクを記載したメールをすぐにお届けします。
            </p>
            <br>
            <!-- メール送信のためのフォームを配置-->
            <form action="" method="POST" class="text-center">
              {% csrf_token %}
              <!-- formに格納されているインプットボックスとラベルを出力-->
              {{form}}
              <!-- 送信ボタン -->
              <input type="submit" value="メールを受け取る" /><br>
            </form>
            <br>
            <!-- トップページへのリンク-->
            <a href="{% url 'status_app:index' %}">Photo Gallery</a>
            <hr>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="ja">
  <head>
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>パスワードがリセットされました。</h2>
      <p>
        Your Password has been set. You may go ahead and login
      </p>
      <br>
      <!-- トップページへのリンク-->
      <a href="{% url 'status_app:index' %}">Photo Galleryのトップページへ</a>
    </div>
  </body>
</html>

accounts/templates/password_reset_form.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- マージン、パディング、背景色を設定するCSSを定義 -->
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>Photo Gallery</h2>
      <h4>
        新しいパスワードを2回入力してください。これにより、
        正しく入力できたことが確認されます。
      </h4>
      <br />
      <!-- フォームを配置-->
      <form action="" method="POST">
        {% csrf_token %}
        <!-- formに格納されている要素をすべてを出力 -->
        {{form}}
        <!-- パスワードリセットボタン-->
        <input type="submit" value="パスワードリセット"/>
      </form>
    </div>
  </body>
</html>

accounts/templates/password_reset_sent.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Send password reset{% endblock %}

      {% block contents %}
      <!-- 水平線-->
      <hr>
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる
               列の上下パディングはpy-4-->
          <div class="col offset-2 py-4">
              <h5>パスワードのリセット手順をメールで送信しました。
                  メールはすぐに届きます。</h5>
              <br>
              <h6>
                メールが届かない場合は、登録済みのメールアドレスであるかを
                確認し、迷惑メールフォルダーも確認してみてください。</h6>
              <br>
              <!-- トップページへのリンク-->
              <a "{% url 'status_app:index' %}">Photo Gallery</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/signup.html
<!-- ベーステンプレートを適用する -->
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    

    <!-- <link rel="canonical"...>を削除 -->    

    <!-- Bootstrap core CSS -->
    <!--
    Bootstrap core CSSを読み込むコードをBootstrapからコピーして
    <link>タグを書き換え -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
          crossorigin="anonymous">
    

    
    <!-- Custom styles for this template -->
    <!-- 「static/css/signin.css」の読み込み -->
    <link href={% static "css/style.css" %}
          rel="stylesheet">
  </head>
  <body id="login1" >    
    <main class="form-signin">
      <!-- Bootstrapのグリッドシステム -->
      <hr>
      <article>        
        <p>下記メールフォームをご記入いただき、「送信する」ボタンを押してください。</p>
        <p>「<span class="must">※</span>」は必須項目です。</p>
        <section>
          <h2>マイページ作成</h2>
           <div class="signup-container mannnaka ">
            <!-- サインアップのフォームを配置 -->
            <form method = "post" class="form-control">
              {% csrf_token %}
              <!-- formからフィールドを取り出す -->
             <table>
              {% for field in form %}
               
                 <!-- ラベルを出力 -->
                 
                  <tr>
                    {% if field.label == 'ユーザー名' or field.label == 'メールアドレス' or field.label == '趣味' or  field.label == 'パスワード' or field.label == 'パスワード(確認用)' %}
                    <th><span class="must">※</span>{{ field.label_tag }}</th>
                    <td>{{ field }}</td>
                    {% else %}
                    <th>{{ field.label_tag }}</th>
                    <td>{{ field }}</td>
                    {% endif %}
                  </tr>
                 <!-- <input>タグを出力 -->
                
                 <!-- help_textを出力 -->
                 
                   
                 
                 <!-- エラー発生時のテキストerrorsを出力 -->
                 {% for error in field.errors %}
                   <p style="color: red">{{ error }}</p>
                 {% endfor %}
                
             {% endfor %}
            </table>
            <!--時間があれば注意書きとリテラシーなど含めた文章読んだ上でのユーザー同意のためのチェック
            を作りたい-->
            <br>
              <a style="color:red">
                ※メールアドレスはパスワードをリセットする際に必要になりますので、
                登録をお願いします。
              </a>
              <!-- Sign upボタンを出力 -->
              <input type="submit" value="Sign up">
            </form>
          </div>
            <!-- トップページのリンクテキスト -->
            <br>
            
          </dv>
        </dv>
      </dv>
      </section>
      </article>
      </main>
      
    </body>
    </html>

accounts/templates/signup_success.html
<!-- ベーステンプレートを適用する -->

<!-- ヘッダー情報のページタイトルを設定する -->

      <!-- Bootstrapのグリッドシステム -->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-4を入れる
               列の上下パディングはpy-4 -->
          <div class="col offset-4 py-4">
            <h3>登録が完了しました</h3>
            <!-- ログインページのリンクテキスト -->
            <p><a href="{% url 'accounts:login' %}">ログインはこちら</a><p>
          </dv>
        </dv>
      </dv>
      