accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    
    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
    
]

kadaiproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('status_app.urls')),
    
    path('',include('accounts.urls')),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),



    
    
]

status_app/urls.py
from django.urls import path
from . import views
#URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name ='status_app'
#URLパターンを登録するためのリスト
urlpatterns = [
    
   path('course/', views.CourseView.as_view(),name='course'),
   
    path('user-list/<int:user>',
         views.UserView.as_view(),
         name='user_list'),
   path('access/', views.AccessView.as_view(),name='access'),
    
    #http(s):// ホスト名/以下のパスが''(無し)の場合
    #viewsモジュールのindexviewを実行
    #URLパターン名は'index'
    path('user/', views.MyIndexView.as_view(),name='index')
]

status_app/models.py
from django.db import models
# accountsアプリのmodelsモジュールからCustomUserをインポート
from accounts.models import CustomUser


class CategoryAppend(models.Model):
    '''投稿されたデータを管理するモデル
    '''
    
    CATEGORY =(('comic','漫画'),
               ('anime','アニメ'),
               ('game','ゲーム'),
               ('music','音楽'),
               ('sports','スポーツ'),
               ('sonota','その他'))
    # CustomUserモデル(のuser_id)とPhotoPostモデルを
    # 1対多の関係で結び付ける
    # CustomUserが親でPhotoPostが子の関係となる
    user = models.ForeignKey(
        CustomUser,
        # フィールドのタイトル
        verbose_name='ユーザー',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE,
        related_name='categories'
        )
    category = models.CharField(
        verbose_name='趣味',# フィールドのタイトル
            max_length=20,
           choices=CATEGORY,
           
           )
    
    
    # イメージのフィールド2
    append_content1 = models.CharField(
        verbose_name='詳細',# フィールドのタイトル
        max_length=50,
        blank=True,            # フィールド値の設定は必須でない
        null=True 
    )
    append_image1 = models.ImageField(
        verbose_name='画像',# フィールドのタイトル
        upload_to = 'photos',
        blank=True,            # フィールド値の設定は必須でない
        null=True # MEDIA_ROOT以下のphotosにファイルを保存  
        )
    
    def __str__(self):
        return str(self.category)
class ContentAppend(models.Model):
    
    Category = models.ForeignKey(
        CategoryAppend,
        verbose_name='趣味',
        on_delete=models.CASCADE
    )
    
    append_content2 = models.CharField(
        verbose_name='追加詳細',# フィールドのタイトル
        max_length=50,
    )
    
class ImageAppend(models.Model):
    
    Category= models.ForeignKey(
        CategoryAppend,
        verbose_name='趣味',
        on_delete=models.CASCADE 
    )
    append_image2 = models.ImageField(
        verbose_name='追加画像',# フィールドのタイトル
        upload_to = 'photos',
        # MEDIA_ROOT以下のphotosにファイルを保存  
        )
    
        
    

    
    

status_app/forms.py
from django.forms import ModelForm

from .models import CategoryAppend

class CategoryForm(ModelForm):
    '''ModelFormのサブクラス'''
    class Meta:
        '''ModelFormのインナークラス
        
        Attributes:
          model: モデルのクラス
          fields: フォームで使用するモデルのフィールドを指定
        '''
        model = CategoryAppend
        fields = ['category', 'append_content1', 'append_image1']
    
    

status_app/views.py
from django.shortcuts import render, redirect
# django.views.generic.baseから　TemplateViewをインポート
from django.views.generic.base import TemplateView
#TemplateViewはすでに色々継承されているクラスでtemplatesの場所を読み込んでいる
from django.views.generic import ListView ,CreateView,DetailView


from django.urls import reverse_lazy

from accounts.models import CustomUser
from .models  import CategoryAppend
from .forms import CategoryForm


class MyIndexView(ListView):
    '''トップページのビュー
    
    テンプレートのレンダリングに特化したTemplateViewを継承
    
    Attributes:
        template_name レンダリングするテンプレート
        '''
    model = CategoryAppend
    
    #append_content1, append_image1, category, contentappend, id, imageappend, user, user_id
    #index.htmlをレンダリングする
    template_name = 'index.html'
    STATIC ='static/'
    
    
    def get_queryset(self):
    
        queryset = CategoryAppend.objects.filter(
        user=self.request.user)
        return queryset

class AccessView(CreateView):
    '''トップページのビュー
    
    テンプレートのレンダリングに特化したTemplateViewを継承
    
    Attributes:
        template_name レンダリングするテンプレート
        '''
    model = CategoryAppend
    form_class = CategoryForm
    #index.htmlをレンダリングする
    success_url = reverse_lazy('status_app:index')
    template_name = 'access.html'
    STATIC ='static/'  
    
    
    
    
    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う
        
        parameters:
          form(django.forms.Form):
            form_classに格納されているPhotoPostFormオブジェクト
        Return:
          HttpResponseRedirectオブジェクト:
            スーパークラスのform_valid()の戻り値を返すことで、
            success_urlで設定されているURLにリダイレクトさせる
        '''
        # commit=FalseにしてPOSTされたデータを取得
        data = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        data.user = self.request.user
        # 投稿データをデータベースに登録
        data.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)
class CourseView(ListView):
    '''トップページのビュー
    
    テンプレートのレンダリングに特化したTemplateViewを継承
    
    Attributes:
        template_name レンダリングするテンプレート
        '''
    model = CustomUser
    
    #index.htmlをレンダリングする
    template_name = 'course.html'
    STATIC ='static/'

class UserView(ListView):
    '''トップページのビュー
    
    テンプレートのレンダリングに特化したTemplateViewを継承
    
    Attributes:
        template_name レンダリングするテンプレート
        '''
    #Gallery.htmlをレンダリングする
    template_name = 'index2.html'
    STATIC ='static/'
    def get_queryset(self):
    
            id=self.kwargs['user']
            user_list = CategoryAppend.objects.filter(
            
            user_id=id)
            return user_list

status_app/templates/access.html
{% extends 'base.html' %}
{% load static %}
{% block bg%}index1{% endblock %}
{% block main%}

  <!-- Bootstrapのグリッドシステム -->

      
    
    
      
      
          <section id="point">
        
            <h2>趣味追加</h2>
        
            
            <form method = "post" enctype="multipart/form-data" class="form-control">
              {% csrf_token %}
              
              <table id="profile">
                {% for field in form %}
                <tr>
                  <th>{{ field.label_tag }}</th>
                  <td>{{ field }}</td>
                </tr>
                {% endfor %}
                <button type="submit">追加する</button>
              </table>
               </figure>
            </section>
    {% endblock %}

    

status_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<meta charset="UTF-8">
<meta property="og:title" content="自己紹介">
<meta property="og:description" content="自己紹介">
<meta property="og:image" content="images/main_visual.jpg">
<title>効果測定</title>


<link href={% static 'css/style.css' %} 
rel="stylesheet" 
>
<link rel="stylesheet" 
href={% static 'css/font-awesome.min.css' %}>
<link rel="shortcut icon" 
href={% static 'favi.ico' %}>
<link rel="apple-touch-icon" href={% static 'webclip152.png' %}>
</head>
<body id="{% block  bg %}{% endblock %}">
<div id="fb-root"></div>

  
  <!--ヘッダー-->
  
  <header>
    
      <nav id="global_navi">
        <ul class="sticky">
          <li class="current1"><a href="{% url 'status_app:index' %}">自己紹介</a></li>
          <li class="current2"><a href= "{% url 'status_app:course' %}" >みんなの紹介一覧</a></li>
          
          <li class="current3"><a href= "{% url 'accounts:logout' %} ">ログアウト</a></li>
        </ul>
      </nav>
    
    

    <h1><a ><img src= {% static 'images/gg.jpg' %}  alt="背景" ></a></h1>
   
      
        

    
  </header>
  <!--main-->
  <!--メインビジュアル画像-->
  {% block  visual %}{% endblock %}

  <!--/メインビジュアル画像-->

  <div id="wrapper">
    <!--メイン-->
    <div id="main">
      <div id="breadcrumb">
        <ol>
          <li><a href="{% url 'status_app:index' %}">HOME</a></li>
          <li>自己紹介</li>
        </ol>
      </div>
      {% block  main %}{% endblock %}
    </div>
    <aside id="sidebar">
      <section id="side_banner">
        <h2>インスタ　LINE</h2>
        <ul>
          <li><a href="https://www.instagram.com/keke_20050901?igsh=dDExNHBmeWYwb2hh&utm_source=qr" target="_blank"><img src={% static 'images/insta.png' %} alt="インスタ"></a></li>
          <li><a href="https://line.me/ti/p/F1Kyjy3CqK" target="_blank"><img src={% static 'images/line.png' %} alt="line"></a></li>
        </ul>

      </section>
    
      <section id="side_contact">
        <h2>お話がある方・質問がある方</h2>
        <address><i class="fa fa-phone"></i><a href="tel:08020594144">08020594144</a></address>
        <p>※スマホで見ている方は電話番号のほうをクリック</p>
        <p><a href="contact.html" class="contact_button">質問ボックス</a></p>
      </section>
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://bloom.ne.jp" data-text="あなただけのフラワーアレンジメント教室Bloom">Tweet</a>
      
    </aside>
    <!--/サイド-->
  </div>
  <!--/wrapper-->

  <!--フッター-->
  <footer>
    <div id="footer_nav">
      <ul>
        question_list
        <li><a href="{% url 'status_app:index' %}">自己紹介</a></li>
      
        
        
      </ul>
    </div>
    <small>&copy; 2015 Bloom.</small>
  </footer>
  <!--/フッター-->

</body>
</html>

  

status_app/templates/course.html
{% extends 'base.html' %}
{% load static %}
{% block  bg %}course1{% endblock %}
{% block  main %}
<style>
    /* 全体のリセット */
    main {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background: #f4f4f4;
    }
  
    .container {
      background: #fff;
      border-radius: 12px;
      box-shadow: 0 8px 15px rgba(0, 0, 0, 0.1);
      padding: 20px 30px;
      width: 100%;
      max-width: 400px;
      text-align: center;
      margin: auto;
      margin-top: 50px;
    }
  
    /* <ul>全体のスクロール設定 */
    #data {
      max-height: 200px; /* スクロール可能な最大の高さ */
      overflow-y: auto; /* 縦スクロールを有効化 */
      border: 1px solid #ddd; /* 外枠のボーダー */
      border-radius: 8px;
      padding: 10px;
      margin-top: 10px;
      background-color: #f9f9f9;
    }
  
    /* 各<li>要素のスタイル */
    #data li {
      list-style: none;
      padding: 10px;
      margin: 5px 0;
      border: 1px solid #ccc; /* 各項目を区切るボーダー */
      border-radius: 4px;
      background-color: #fff;
      transition: background-color 0.2s;
    }
  
    #data li:hover {
      background-color: #f0f0f0; /* ホバー時の色変更 */
    }
  
    #data li a {
        margin: 10px 0;
  padding: 10px;
  background: rgba(0, 0, 0, 0.6);
  border-radius: 10px;
  box-shadow: 5px 8px 9px rgba(0, 0, 0, 0.4);
  color: #eaeaea;
  transition: color 0.3s ease, transform 0.2s ease;
  font-size: 30px;
    }
    #data li a::before{
        color: #00d4ff;
        font-weight: bold;
    }
    #data li a:hover {
        color: #00d4ff;
        transform: scale(1.05);
        cursor: pointer;
    }
  </style>
</head>
<main id="user">
<div class="container">
<h1>ユーザー一覧</h1>
<ul id="data">
    {% for record in object_list %}
  <li ><a href="{% url 'status_app:user_list' user=record.id %}">{{record.username}}</a></li>
  {% endfor %}
  
</ul>
</div>
</main>

      {% endblock %}

status_app/templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block  bg %}gallery1{% endblock %}
{% block  main %}
      
      <article id="gallery">
       <h3>やってるゲーム🎮</h3>
       <table>
         <tr>
          <th>ゲーム種類</th>
          <th>ゲーム名</th>
          <th>キャラ名</th>
         </tr>
         <tr>
          <th rowspan="3">🥊格闘ゲーム🥊</th>
          <td id="st6"><img  src={% static 'images/st6.png' %} >
             </td> 
          <td id="st61"><img  src={% static 'images/kin-removebg-preview.png' %}>
          <h4>キンバリー</h4></td>
         </tr>
         <tr>
          <td id="gi"> <img src={% static 'images/640px-Guilty_gear_logo-removebg-preview.png' %} ></td>
          <td id="gi2"><img src={% static 'images/gi2.jpg' %} >  
            <h4>シン</h4></td>
    
         </tr>
         <tr>
            <td id="suma"> <img src={% static 'images/suma-removebg-preview.png' %} ></td>
            <td id="suma2"><img src={% static 'images/samusu-removebg-preview.png' %} > 
              <h4>ダークサムス</h4></td>
           
           </tr>
           <tr id="none">
          <th rowspan="2">FPS</th>
          <td><img src={% static 'images/73979561-7da4-405f-94db-a41dd73a9d38.png' %} ></td>
          
         </tr>
         <tr id="none">
          <th id="sizi"><img src={% static 'images/OIP-removebg-preview.png' %} ></th>
        
         </tr>
        

        </table>
        
      </article>
      
      {% endblock %}

    

status_app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block  bg %}index1{% endblock %}


  
  {% block main %}
      <style>
        .hidden {
        display: none;
          }
      </style>
      <section id="point">        
        <table id="profile">
          {% for data in object_list %}
          <div hidden>{{data.category}}</div>
          {% endfor %}
          <tr>
            <th>ニックネーム</th>
            <td class="font-1">{{user.username}}</td>
          </tr>
          
          <tr> 
            <th>趣味</th>
            <td id="hobbies">
              <a id="category"></a>
              <a class="append" href="{% url 'status_app:access' %} "  ><img  src={% static 'images/append.png' %} ></a>
            </td>
          </tr>
          <script>
            const divElements = document.querySelectorAll('div[hidden]');
        
        // div 要素のテキストをリスト化
        const divTexts = Array.from(divElements).map(div => div.textContent.trim());
        
        // 重複を削除
        const uniqueValues = [...new Set(divTexts)];
        
        // リストを表示
        const currentListElement = document.getElementById("category");
        currentListElement.innerHTML = uniqueValues.map(value => `<h3>${value}</h3>`).join("");
        if (uniqueValues.length === 6) {
            const appendLink = document.querySelector('.append');
            appendLink.classList.add('hidden'); // 非表示にするクラスを追加
        }
      </script>
    
        </table>
        
      
          
         
          
       
           </figure>
        </section>
        {% endblock %}
    
        
       
    

    

status_app/templates/index2.html
{% extends 'base.html' %}
{% load static %}
{% block  bg %}index1{% endblock %}


  
  {% block main %}
      <style>
        .hidden {
        display: none;
          }
      </style>
      <section id="point">        
        <table id="profile">
          {% for data in object_list %}
          <div hidden>{{data.category}}</div>
          {% endfor %}
          <li>
            {% for data in object_list %}
            <ul hidden>
            {{data.user.username}}
           </ul>
           {% endfor %}
          </li>
          <tr>
            <th>ニックネーム</th>
            
            <td id="user"></td>
            
          </tr>
          
          <tr> 
            <th>趣味</th>
            <td id="hobbies">
              <a id="category"></a>
              
            </td>
          </tr>
          <script>
            const divElements = document.querySelectorAll('div[hidden]');
        
            // div 要素のテキストをリスト化
            const divTexts = Array.from(divElements).map(div => div.textContent.trim());
            const ulElements = document.querySelectorAll('ul[hidden]');
        
            // div 要素のテキストをリスト化
            const ulTexts = Array.from(ulElements).map(div => div.textContent.trim());
        // 重複を削除
        const currentListElement = document.getElementById("category");
        const userlistElment = document.getElementById("user");
        function display(data,currentListElement) {
          
        
        const uniqueValues = [...new Set(data)];
        
        // リストを表示
       currentListElement.innerHTML = uniqueValues.map(value => `<h3>${value}</h3>`).join("");
      }
      display(divTexts,currentListElement)
      display(ulTexts,userlistElment)
      </script>
    
        </table>
        
      
          
         
          
       
           </figure>
        </section>
        {% endblock %}
    
        
       
    

    